[default]
DEBUG = false
EXTENSIONS = [
  "blog.extensions.web:init_app"
]

[development]
DEBUG = true
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
EXTENSIONS = [
  "blog.extensions.web:init_app",
  "blog.extensions.toolbar:init_app"
]

[production]